IIT_Outlook_Oauth-master/IITG_Outlook/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^authentication/', include('authentication.urls', namespace='authentication')),

]

gsecWorkStatus/urls.py
from django.contrib import admin
from django.conf.urls import url
from . import views
from gsecWorkStatus import views
from django.urls import path
from  django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required

app_name = 'candidate'



urlpatterns = [
    # url(r'^cultural/$', views.cultural, name='cultural'),
    url(r'^addagendaforgs/$', views.create_Agenda1, name='createagenda'),
    url(r'^home/$', views.home, name='vp'),
    url(r'^jugaad/(?P<pname>[\w\-]+)/$', views.jugaad, name='jugaad'),
    url(r'name/(?P<pname>[\w\-]+)/vote/$', views.vote, name='vote'),
    url(r'^home/vote/$', views.voteh, name='voteh'),
    url(r'name/(?P<pname>[\w\-]+)/$',views.vp,name='gs'),
    url(r'^$', views.home, name='index'),
    # url(r'^technical/$', views.technical, name='technical'),
    # url(r'^welfare/$', views.welfare, name='welfare'),
    # url(r'^senator1/$', views.senator1, name='senator1'),
    # url(r'^hab/$', views.hab, name='hab'),
    # url(r'^sports/$', views.sports, name='sports'),
    url(r'^login/$',views.user_login,name='login'),
    url(r'^register/$',views.register,name='register'),
    url(r'^addagenda/$',views.addagenda,name='addagenda'),
    url(r'^verify/$',views.approvestatus,name='verify'),
    url(r'^verified/(?P<pk>[0-9]+)/$',views.verifysatus,name='verified'),
    url(r'^disapprove/(?P<pk2>[0-9]+)/$',views.disapprove,name='disapprove'),
     # url(r'^checkurl/$',views.checklogin(),name='checklogin'),
    url(r'^update/(?P<pk>[0-9]+)/$',login_required(views.UpdateAgenda.as_view()),name='updatestatus'),
    url(r'^comment/(?P<pk1>[0-9]+)/$',views.updatestatus,name='comment'),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^change_password/$',views.change_password,name='changepswd'),
    url(r'^compare/$',views.compare,name='compare'),
    url(r'^comparesenator/$',views.comparesenator,name='comparesenator'),
    url(r'^comparepast/$',views.comparepast,name='comparepast'),

]

gsecmeter/urls.py
from django.contrib import admin
from django.conf.urls import url, include

# two line below to import static
from django.conf import settings
from django.conf.urls.static import static


# Next to line to handle static file URLS

urlpatterns = [
    url(r'^gsec/admin/', admin.site.urls),
    url(r'^gsec/authentication/', include('authentication.urls', namespace='authentication')),
    url(r'^gsec/', include('gsecWorkStatus.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

gsecWorkStatus/forms.py
from django import forms
from django.forms import ModelForm,Textarea,Select
from gsecWorkStatus.models import  UserProfileInfo,User,agenda
from django.contrib.auth.models import User
from django import forms
from django.forms import (formset_factory, modelformset_factory)


Agenda_choices= [
                ('Completed', 'Completed'),
                ('Ongoing-Long-Term', 'Ongoing-Long-Term'),
                ('Ongoing-Short-Term', 'Ongoing-Short-Term'),
                ('Not-Started', 'Not-Started'),
                ('Broken', 'Broken'),
                ('Not-Evaluated', 'Not-Evaluated'),
                ('Not-Evaluated-Subjective', 'Not-Evaluated-Subjective'),
]

# class Agendaform(forms.ModelForm):
#     class Meta():
#         model=agenda
#         Title = forms.CharField(
#         # label='Title',
#             widget=forms.TextInput(attrs={
#                 'class': 'form-control',
#                 'placeholder': 'Enter Your Agenda here'
#             })
#         )
#         AgendaCategory = forms.CharField(
#         # make it drop down
#         # label='Book Name',
#             widget=forms.TextInput(attrs={
#                 'class': 'form-control',
#                 'placeholder': 'Enter Book Name here'
#             })
#         )
#         Description = forms.CharField(
#         # label='Book Name',
#             widget=forms.Textarea(attrs={
#                 'class': 'form-control',
#                 'rows':'4',
#                 'placeholder': 'Enter Description here'
#             })
#         )
#         Status = forms.CharField(
#         # make it drop down
#         # label='Book Name',
#             widget=forms.TextInput(attrs={
#                 'class': 'form-control',
#                 'placeholder': 'Enter Book Name here'
#             })
#         )
#         Comment = forms.CharField(
#         # make it drop down
#         # label='Book Name',
#             widget=forms.TextInput(attrs={
#                 'class': 'form-control',
#                 'placeholder': 'Enter Comment here'
#             })
#         )
# "faccho dhang se padho"
Agendaformset = modelformset_factory(
            agenda,

            fields=('title','agendaCategory','unapprovedComment','unapprovedStatus','description'),
            extra=1,
            widgets={
                'title':forms.TextInput(attrs={
                    'class': 'form-control',
                    'placeholder': 'Enter Your Agenda Name here',
                    'required':True
                }),
                'agendaCategory':forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter Agenda category here'
            }),
                'unapprovedComment':forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter Comment here'
            }),
                'description':forms.Textarea(attrs={
                'class': 'form-control',
                'rows':'4',
                'placeholder': 'Enter Description here'
            })
            }

        )


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    # first_name =
    class Meta():
        model =User
        fields = ('username','email','password','first_name','last_name')
        labels = {
            # "username":("Webmail username"),
            "email":("Webmail id"),
            "first_name": ("User Type"),
            "last_name" : ("Full Name")

        }

        type = (

            ('CIS','CIS'),
            ('GS','GS'),
        )
        widgets = {'first_name': Select(choices=type)}

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('post_description','image','youtube','pdf')
        labels = {
            "image": ("Profile Pic"),
            "youtube": ("Youtube video link"),
            "pdf":("Agenda Pdf")

        }


class AgendaForm(forms.ModelForm):
    class Meta():
        model=agenda
        fields = ['user','title','agendaCategory','description','StatusCategory','unapprovedComment','unapprovedStatus',]
        widgets = {
            'description': Textarea,
            'representativeComments':Textarea(attrs={'rows': 3 }),
        }

class UpdateStatusForm(forms.ModelForm):
    class Meta():
        model = agenda
        fields = ['title','unapprovedStatus','unapprovedComment','status']

gsecWorkStatus/views.py
from django.shortcuts import render,redirect
import pickle
import os
from django.contrib import messages
from graphos.sources.simple import SimpleDataSource
from graphos.renderers import gchart
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from  django.views import generic
from django.http import HttpResponse,HttpResponseRedirect
from  django.contrib.auth import authenticate,login,logout
from django.urls import reverse,reverse_lazy
from django.contrib.auth.decorators import login_required
from gsecWorkStatus.models import User,UserProfileInfo,agenda,votes
from gsecWorkStatus.forms import UserProfileInfoForm,UserForm,AgendaForm,UpdateStatusForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.shortcuts import HttpResponse, reverse, redirect


from django.views import generic

from .forms import (
    Agendaformset
)
# from .models import Agenda1

@login_required
def create_Agenda1(request):
    # a=agenda(request.POST)
    if request.user.first_name == "GS":
        template_name = 'create_Agenda1.html'
        # heading_message = 'Formset Demo'
        if request.method == 'GET':
            formset = Agendaformset(queryset=agenda.objects.none())
        elif request.method == 'POST':
            formset = Agendaformset(request.POST)
            if formset.is_valid():
                for form in formset:
                    if(form.is_valid()):
                    # form.user=request.user.username
                        agd=form.save(commit=False)
                        agd.user=request.user
                        agd.StatusCategory=agd.unapprovedStatus
                        agd.save()
                return render(request, 'agendaadded.html', {'some_flag': True})
                # return HttpResponse("agenda added")
            else:
                return render(request,'agendaadded.html',{'flag':True})
        return render(request, template_name, {'formset': formset})
    else:
        return HttpResponse("You are not allowed to visit this page :(    contact - Rishikesh   ")

# sign_in_url = get_signin_url(redirect_uri)


# def gettoken1(request):
#     #################################
#     # Set redirect after saving token
#     redirect_url = request.GET["next"]
#     ################################
#
#     # get Token from code
#     auth_code = request.GET['code']
#     redirect_uri = request.build_absolute_uri(reverse('authentication:gettoken'))
#     token = get_token_from_code(auth_code, redirect_uri)
#     access_token = token['access_token']
#
#     # Save the token in session
#     request.session['access_token'] = access_token
#
#     # redirect_url = request.session.get('redirect_url', None)
#
#     if redirect_url is None:
#
#         #####################
#         # Get user from token
#         user = get_me(access_token)
#
#         return HttpResponse("Token: %s<br>Name: %s<br>Roll Number: %s<br> Mail: %s" % (
#         access_token, user['displayName'], user['surname'], user['mail']))
#     else:
#         return redirect(redirect_url)

@login_required(login_url='authentication:home')
def jugaad(request,pname):
    user_id = request.user.id
    item_id = pname
    redirect_uri = request.build_absolute_uri('')
    v = votes.objects.filter(item_id=item_id, user_id=user_id)
    if (len(v) > 0):
        return redirect(redirect_uri)
    m = votes(item_id=item_id, user_id=user_id)
    m.save()
    v = votes.objects.filter(item_id=item_id)
    return redirect(redirect_uri)
def vote(request,pname):
    if request.method == 'GET':

        if (request.GET['query'] == 'vote'):
            def nvote(request):
                item_id = request.GET['item_id']
                user_id = request.user.id
                v = votes.objects.filter(item_id=item_id, user_id=user_id)
                if (len(v) > 0):
                    return HttpResponse(-1)
                m = votes(item_id=item_id, user_id=user_id)
                m.save()
                v = votes.objects.filter(item_id=item_id)
                return HttpResponse(len(v))
            return nvote(request)
        elif request.GET['query']=='votecount':
            item_id=request.GET['item_id']
            total_votes=0
            v=votes.objects.filter(item_id=item_id)
            return HttpResponse(len(v))
            # return HttpResponse(len(v))
        # post_id = request.GET['post_id']
        # likedpost = Post.obejcts.get(pk=post_id)  # getting the liked posts
        # m = Like(post=likedpost)  # Creating Like Object
        # m.save()  # saving it to store in database
        return HttpResponse("0")  # Sending an success response
    else:
        return HttpResponse("Request method is not a GET")

def voteh(request):
    if request.method == 'GET':
        if (request.GET['query'] == 'vote'):
            def nvote(request):
                item_id = request.GET['item_id']
                user_id = request.user.id
                v = votes.objects.filter(item_id=item_id, user_id=user_id)
                if (len(v) > 0):
                    return HttpResponse(-1)
                m = votes(item_id=item_id, user_id=user_id)
                m.save()
                v = votes.objects.filter(item_id=item_id)
                return HttpResponse(len(v))
            return nvote(request)
        elif request.GET['query'] == 'votecount':
            item_id = request.GET['item_id']
            total_votes = 0
            v = votes.objects.filter(item_id=item_id)
            return HttpResponse(len(v))
                # return HttpResponse(len(v))
            # post_id = request.GET['post_id']
            # likedpost = Post.obejcts.get(pk=post_id)  # getting the liked posts
            # m = Like(post=likedpost)  # Creating Like Object
            # m.save()  # saving it to store in database
        return HttpResponse("0")  # Sending an success response
    else:
        return HttpResponse("Request method is not a GET")
    #             Title = form.cleaned_data.get('Title')
    #             AgendaCategory = form.cleaned_data.get('AgendaCategory')
    #             Description = form.cleaned_data.get('Description')
    #             Status = form.cleaned_data.get('Status')
    #             Comment = form.cleaned_data.get('Comment')
    #             # save book instance
    #             if Agenda1:
    #                 a=Agenda1(Title=Title,
    #                      AgendaCategory=AgendaCategory,
    #                      Description=Description,
    #                      Status=Status,
    #                      Comment=Comment)
    #                 a.save()
    #         return redirect('store:book_list')
    #
    # return render(request, template_name, {
    #     'formset': formset,
    #     'heading': heading_message,
    # })

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DICT_DIR = os.path.join(BASE_DIR, 'script_dir', 'dict_dir')

post_list = ['Vice_President', 'Technical', 'Cultural', 'Sports', 'Welfare', 'HAB','senator1']
post_name = ['vp', 'technical', 'cultural', 'sports', 'welfare', 'hab','senator1']


def comparechart(post1,post2,compare1,compare2):
    data = []
    templist=['status']
    templist.append(post1)
    templist.append(post2)
    data.append(templist)
    d1={}
    d2={}
    d1=draw_chart1(compare1)
    d2=draw_chart1(compare2)
    candidate1 = d1['data']
    candidate2 = d2['data']
    # agendapercent=[]

    # ['completed', 20, 40, 20]
    # ['Completed', 31.03448275862069],
    for i in range (1,8):
        agendapercent=[]
        agendapercent.append(candidate1[i][0])
        agendapercent.append(candidate1[i][1])
        agendapercent.append(candidate2[i][1])
        if agendapercent[1] or agendapercent[2]:
            data.append(agendapercent.copy())

    print("abc:")
    print(data)
    data_source = SimpleDataSource(data=data)
    # Chart object
    chart = gchart.ColumnChart(data_source)
    return chart


# [["Completed" , count], ...]
def draw_chart(post_dict):
    data = []
    data.append(['status', 'No of task'])
    for status, temp_dict in post_dict.items():
        data.append([status, len(temp_dict)])

    print(data)
    # DataSource object
    # options = { 'width': 400,'height': 240,'title': "Toppings I Like On My Pizza",'colors': ["#00b300", "#e6693e", "#ec8f6e", "#f3b49f", "#e60000"]}
    data=[
            ['status', 'General Secretary, Technical Board 2018-19', 'Vice-President, Gymkhana Council 2017-18'],
            ['Completed', 0.0, 31.03448275862069],
            ['Ongoing-Long-Term', 0.0, 0.0],
            ['Ongoing-Short-Term', 0.0, 0.0],
            ['Not-Evaluated', 0.0, 20.689655172413794],
            ['Not-Evaluated-Subjective', 0.0, 0.0],
            ['Not-Started', 100.0, 37.93103448275862],
            ['Broken', 0.0, 10.344827586206897]
          ]

    data_source = SimpleDataSource(data=data)
    # Chart object
    chart = gchart.ColumnChart(data_source)
    return chart


def compare(request):
    if request.method=="POST":
        compare1=request.POST.get('compare1')
        compare2 = request.POST.get('compare2')



        obj1 = agenda.objects.filter(user__userprofileinfo__post_description=compare1)
        obj2 = agenda.objects.filter(user__userprofileinfo__post_description=compare2)
        print(compare1)
        print(compare2)


        chart=comparechart(compare1,compare2,obj1,obj2)
        # print(chart)
        return render(request,'gsecWorkStatus/compareview.html',{'chart':chart})
        # return HttpResponseRedirect(reverse('candidate:vp'))
    else:
        members = UserProfileInfo.objects.all()

        senators = User.objects.filter(username__contains="senator")
        return render(request, 'gsecWorkStatus/compare.html', {'members': members, 'senators': senators})
    # if request.method == "POST":

def pastchart(agendas):

gsecWorkStatus/templates/gsecWorkStatus/Cultural.html
{% extends 'gsecWorkStatus/base.html' %}
{%block cultural_selected%}style="background-color: #810496;"{%endblock%}

gsecWorkStatus/templates/gsecWorkStatus/HAB.html
{% extends 'gsecWorkStatus/base.html' %}
{%block hab_selected%}style="background-color: #810496;"{%endblock%}

gsecWorkStatus/templates/gsecWorkStatus/Vice_President.html
{% extends 'gsecWorkStatus/base.html' %}


{%block vp_selected%}style = "background-color: #810496;"{%endblock%}

gsecWorkStatus/templates/gsecWorkStatus/addagenda.html
{% extends 'gsecWorkStatus/base1.html' %}

{%block info_agenda %}

    {% if registered %}
        <h1>thanks!records updated</h1>
    {% else %}
        <h3 align="center" style="font-family: 'Tibetan Machine Uni'">Add Agenda </h3>
        <div class="container" >
        <div class="row"><div class="col-lg-3"></div>
        <div class="col-lg-6" style=" border: solid 1px; box-shadow: 2px 2px 2px 2px gray; padding: 2em; margin: 1em; background-color: snow;" >
        <form method="post" action="{% url 'candidate:addagenda' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group ">

            {% for field in agenda_form %}
                <label>{{ field.label_tag }}</label>
                <div > {{ field }}</div>
            {% endfor %}

            </div>
            <div align="center">
            <button type="submit" class="btn btn-primary" style="background-color:#081D40" value="ADD">ADD</button>
                </div>
        </form>
        </div>
            <div class="col-lg-3"></div>
        </div>
        </div>
    {% endif %}

{% endblock %}

gsecWorkStatus/templates/gsecWorkStatus/change_password.html
{% extends 'gsecWorkStatus/base1.html' %}
{% block info_agenda %}
    <div style="margin: 2em; padding: 2em; border: solid 1px; box-shadow: 2px 2px 2px 2px grey">
    <form action="{% url 'candidate:changepswd' %}" method="post">
        {% csrf_token %}    {{ form }}<br>
        <div align="center"><button type="submit" class="btn btn-primary" style="background-color: #081D40">Change Password</button></div>

    </form></div>
{% endblock %}

gsecWorkStatus/templates/gsecWorkStatus/compare.html
{% extends 'gsecWorkStatus/base.html' %}
{%block info_agenda%}
{#    <div style="padding: 0px; border: solid 1px; max-width:90px" align="center"><button class="btn btn-primary" style="">VP</button></div>#}
<style>
 @media only screen and (max-width: 600px) {
    .smallscrn{
        width: auto;
    }
 }
@media only screen and (min-width: 600px) {

    #styledbutton .mobilebtn{
        width: 50%;
    }
    #styledbutton .largebtn{
                width: 60%;
    }
 }
</style>
    <div id="styledbutton">
    <form action="{% url 'candidate:comparepast' %}" method="post">{% csrf_token %}

    <div align="center"><h4 style="font-family: 'Tibetan Machine Uni'">Compare Current GenSec Progress</h4><button type="submit" class="btn btn-primary" name="designation" value="2019-20">Compare Current GenSec</button></form></div>
    </div>
    <h4 align="center" style="font-family: 'Tibetan Machine Uni'">Current Genral Seceratry's progress w.r.t Previous Year</h4>
    <div  style="padding-top: 4em; margin: 1em; ">


<div align="center" id="styledbutton" >
    <div class="btn-group btn-group-justified mobilebtn smallscrn">
      <div class="btn-group" style="margin:  20px; ">
          <form action="{% url 'candidate:comparepast' %}" method="post">{% csrf_token %}
        <button type="submit" class="btn btn-primary" name="designation"  value="Vice-President">VP</button></form>
      </div>
     <div class="btn-group" >
          <form action="{% url 'candidate:comparepast' %}" method="post">{% csrf_token %}
        <button type="submit" class="btn btn-primary" name="designation" value="Hostel Affairs Board">HAB</button></form>
     </div></div> <br>
    <div class="btn-group btn-group-justified mobilebtn smallscrn">
    <div class="btn-group">
          <form action="{% url 'candidate:comparepast' %}" method="post">{% csrf_token %}
        <button type="submit" class="btn btn-primary" name="designation" value="Cultural Board">Cultural</button></form>
      </div>
        <div class="btn-group">
          <form action="{% url 'candidate:comparepast' %}" method="post">{% csrf_token %}
        <button type="submit" class="btn btn-primary" name="designation" value="Welfare Board">Welfare</button></form>
        </div></div><br>
    <div class="btn-group btn-group-justified mobilebtn smallscrn">
        <div class="btn-group" >
          <form action="{% url 'candidate:comparepast' %}" method="post">{% csrf_token %}
        <button type="submit" class="btn btn-primary" name="designation" value="Technical Board">Technical</button></form>
      </div>
        <div class="btn-group">
          <form action="{% url 'candidate:comparepast' %}"  method="post" >{% csrf_token %}
        <button type="submit" class="btn btn-primary" name="designation" value="Sports Board">Sports</button></form>
        </div></div> <br>
{#    </div>#}


    <div class="btn-group btn-group-justified mobilebtn smallscrn" >
      <div class="btn-group">
          <form action="{% url 'candidate:comparepast' %}" method="post">{% csrf_token %}
        <button type="submit" class="btn btn-primary"  name="designation" value="Student Alumni Interaction Linkage">Sail</button></form>
      </div>
     <div class="btn-group">
          <form action="{% url 'candidate:comparepast' %}" method="post">{% csrf_token %}
        <button type="submit" class="btn btn-primary" name="designation" value="SWC">SWC</button></form>
     </div></div> <br>

{#    </div>#}
 
    </div>
{#            <select name="compare1">#}
{##}
{#                {% for person in members  %}#}
{#                    {% if person.post_description != "PG SENATOR 2018-19" and person.post_description != "UG Senator 2018-19" and person.post_description != "Girl Senator 2018-19" %}#}
{#                    <option>{{ person.post_description }}</option>#}
{#                    {% endif %}#}
{#                {% endfor %}#}
{#            </select>#}
{#             #}
{#            <select name="compare2">#}
{#                             {% for person in members  %}#}
{#                    {% if person.post_description != "PG SENATOR 2018-19" and person.post_description != "UG Senator 2018-19" and person.post_description != "Girl Senator 2018-19" %}#}
{#                    <option>{{ person.post_description }}</option>#}
{#                    {% endif %}#}
{#                {% endfor %}#}
{##}
{#            </select>#}
{#         #}
{#        <div align="center"> <button type="submit" class="btn btn-primary" style="background-color: purple">Compare</button></div>#}
{#        </form>#}
{##}
{#    </div>#}
{#    <h3 align="center" style="font-family: 'Tibetan Machine Uni'">Compare Senators</h3>#}
{##}
{#    <div  style="padding-top: 4em; margin: 1em; ">#}
{##}
{#        <form action="{% url 'candidate:comparesenator' %}" method="post" >#}
{#        {% csrf_token %}#}
{##}
{#            <select name="senator1">#}
{##}
{#                {% for person in senators  %}#}
{##}
{#                    <option>{{ person.username }}</option>#}
{##}
{#                {% endfor %}#}
{#            </select>#}
{#             #}
{#            <select name="senator2">#}
{#             {% for person in senators  %}#}
{##}
{#                    <option>{{ person.username }}</option>#}
{##}
{#                {% endfor %}#}
{##}
{#            </select>#}
{#         #}
{#        <div align="center"> <button type="submit" class="btn btn-primary" style="background-color: purple">Compare</button></div>#}
{#        </form>#}
{##}
{#    </div>#}

{% endblock %}

gsecWorkStatus/templates/gsecWorkStatus/verify.html
{% extends 'gsecWorkStatus/base1.html' %}
{% block info_agenda %}
    <style>
        .hidden{
            display: none;
        }
    </style>
    <script>

        function verify(id) {


            $.ajax({
                type: "POST",
                url: "/gsec/verified/"+id+"/",


                data: {
                    id: id,
                    csrfmiddlewaretoken: '{{csrf_token}}'
                },
                success: function () {


                    {#var bid ="#thank"+id;#}
                    var cid ="#agenda"+id;

                    $(cid).css("display","none");

                 },

            });
            console.log("end");
        }
        function dissaprove(id) {

            $.ajax({
                type: "POST",
                url: "/gsec/disapprove/"+id+"/",


                data: {
                    id: id,
                    csrfmiddlewaretoken: '{{csrf_token}}'
                },
                success: function () {


                    {#var bid ="#thank"+id;#}
                    var cid ="#agenda"+id;

                    $(cid).css("display","none");

                 },

            });
            console.log("end");
        }

    </script>

<h3 align="center" style="font-family: 'Tibetan Machine Uni';">Approve Agenda</h3>

<i style="color: red">If you approve any agenda then its Status comment and Agenda Category will be set as per below</i>
<br><br>        <div class="row ">

        {% for agenda in all_agenda  %}

            {% if agenda.StatusCategory != "" %}

                <div class="col-lg-6 container-fluid " id="agenda{{ agenda.pk }}">
                <div class="card bg-light mb-3" style="   max-width: 50rem; padding: 20px;background-color: #EEEEEE; " >

                    <div class="card-header "  ><span style="text-align: right;border: solid 1px;padding: 1px ;margin:5px;" class="expand"> +  </span><strong style="font-weight: bold;">{{ agenda.title }}</strong></div>
{#                        <div class="col-md-2" align="right">+</div>#}

                <div style="display:none;background-color: whitesmoke;padding: 10px;" class="card-body boxcontent">
                <h5 class="card-title">{{ agenda.user.last_name }}</h5>
                <p class="card-text"><b>Comment:</b> {{ agenda.unapprovedComment }}</p>
                <p class="card-text"><b>Status:</b> {{ agenda.unapprovedStatus }}</p>
                    <p class="card-text"><b>Agenda Category :</b> {{ agenda.StatusCategory }} </p>
                    <p class="card-text"><b>Description : </b>{{ agenda.description }}</p>
                    <div class="row">
                        <div  class="col-lg-6">
				                    <button type="submit" value="approve" id="{{ agenda.pk }}" class="btn btn-primary" onclick="dissaprove({{ agenda.pk }})" style="background-color: #081D40;;">Disapprove</button>

		    {#  </form> #}</div>
                        <div align="right" class="col-lg-6">
{#                    <form action="{% url 'candidate:verified' agenda.pk %}" method="post">#}
{#                {% csrf_token %}#}
                    <button type="submit" value="approve" id="{{ agenda.pk }}" class="btn btn-primary" style="background-color: #081D40;" onclick="verify({{ agenda.pk }})">Approve</button>

{#                </form>#}
                        </div></div>

                </div>
                </div>
              </div>
{#                <h1>{{ agenda.user }}</h1>#}
{#                <h2>{{ agenda.title }}</h2>#}
{#                {{ agenda.id }}#}
{#                <li>comment  :   {{ agenda.unapprovedComment }}</li><br>#}
{#                 <li>status  :   {{ agenda.unapprovedStatus }}</li>#}
{#                    <li> status Category : {{ agenda.StatusCategory }}</li>#}
{#                <form action="{% url 'candidate:verified' agenda.pk %}" method="post">#}
{#                {% csrf_token %}#}
{#                <input type="submit" value="approve">#}
{#                </form>#}

            {% endif %}

        {% endfor %}
        </div>
 <script>
      $(document).ready(function(){

        $("footer").addClass("fixed-bottom");
        $(".expand").click(function(){
        $(".boxcontent").eq($('.expand').index(this)).toggle();
        });


    });

    </script>
{%endblock%}